apiVersion: v1
kind: Service
metadata:
  name: chanchito-backend-service
spec:
  selector:
    app: chanchito-backend
  ports:
    - protocol: TCP
      port: 3600 # Puerto interno del clúster
      targetPort: 3600 # Puerto del contenedor
      nodePort: 30001 # Puerto accesible en localhost (puedes cambiarlo si prefieres otro)
  type: NodePort
